#include "loadopengl.h"
#include "logs.h"
#define LOAD_GL_FUNC(type, name)                      \
	name = (type)glfwGetProcAddress(#name);       \
	if (!name) {                                  \
		VERROR("Failed to load %s\n", #name); \
		return false;                         \
	}

PFNGLVERTEXATTRIBIPOINTERPROC glVertexAttribIPointer = NULL;
PFNGLUNIFORM1FPROC glUniform1f = NULL;
PFNGLUNIFORM3FVPROC glUniform3fv = NULL;
PFNGLBUFFERSUBDATAPROC glBufferSubData = NULL;
PFNGLTEXPARAMETERFVPROC glTexParameterfv = NULL;
PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays = NULL;
PFNGLVIEWPORTPROC glViewport = NULL;
PFNGLCLEARCOLORPROC glClearColor = NULL;
PFNGLCLEARPROC glClear = NULL;
PFNGLGENBUFFERSPROC glGenBuffers = NULL;
PFNGLBINDBUFFERPROC glBindBuffer = NULL;
PFNGLBUFFERDATAPROC glBufferData = NULL;
PFNGLCREATESHADERPROC glCreateShader = NULL;
PFNGLSHADERSOURCEPROC glShaderSource = NULL;
PFNGLCOMPILESHADERPROC glCompileShader = NULL;
PFNGLGETSHADERIVPROC glGetShaderiv = NULL;
PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog = NULL;
PFNGLCREATEPROGRAMPROC glCreateProgram = NULL;
PFNGLATTACHSHADERPROC glAttachShader = NULL;
PFNGLLINKPROGRAMPROC glLinkProgram = NULL;
PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog = NULL;
PFNGLGETPROGRAMIVPROC glGetProgramiv = NULL;
PFNGLUSEPROGRAMPROC glUseProgram = NULL;
PFNGLDELETESHADERPROC glDeleteShader = NULL;
PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer = NULL;
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray = NULL;
PFNGLGENVERTEXARRAYSPROC glGenVertexArrays = NULL;
PFNGLBINDVERTEXARRAYPROC glBindVertexArray = NULL;
PFNGLDRAWARRAYSPROC glDrawArrays = NULL;
PFNGLDRAWELEMENTSPROC glDrawElements = NULL;
PFNGLPOLYGONMODEPROC glPolygonMode = NULL;
PFNGLGENTEXTURESPROC glGenTextures = NULL;
PFNGLBINDTEXTUREPROC glBindTexture = NULL;
PFNGLTEXIMAGE2DPROC glTexImage2D = NULL;
PFNGLGENERATEMIPMAPPROC glGenerateMipmap = NULL;
PFNGLTEXPARAMETERIPROC glTexParameteri = NULL;
PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation = NULL;
PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv = NULL;
PFNGLGETERRORPROC glGetError = NULL;
PFNGLUNIFORM1IPROC glUniform1i = NULL;
PFNGLACTIVETEXTUREPROC glActiveTexture = NULL;
PFNGLENABLEPROC glEnable = NULL;
PFNGLCULLFACEPROC glCullFace = NULL;
PFNGLDELETEBUFFERSPROC glDeleteBuffers = NULL;

bool load_gl_functions()
{
	LOAD_GL_FUNC(PFNGLENABLEPROC, glEnable);
	LOAD_GL_FUNC(PFNGLCULLFACEPROC, glCullFace);
	LOAD_GL_FUNC(PFNGLACTIVETEXTUREPROC, glActiveTexture);
	LOAD_GL_FUNC(PFNGLUNIFORM1IPROC, glUniform1i);
	LOAD_GL_FUNC(PFNGLGETERRORPROC, glGetError);
	LOAD_GL_FUNC(PFNGLUNIFORMMATRIX4FVPROC, glUniformMatrix4fv);
	LOAD_GL_FUNC(PFNGLGETUNIFORMLOCATIONPROC, glGetUniformLocation);
	LOAD_GL_FUNC(PFNGLTEXPARAMETERIPROC, glTexParameteri);
	LOAD_GL_FUNC(PFNGLGENERATEMIPMAPPROC, glGenerateMipmap);
	LOAD_GL_FUNC(PFNGLTEXIMAGE2DPROC, glTexImage2D);
	LOAD_GL_FUNC(PFNGLBINDTEXTUREPROC, glBindTexture);
	LOAD_GL_FUNC(PFNGLGENTEXTURESPROC, glGenTextures);
	LOAD_GL_FUNC(PFNGLPOLYGONMODEPROC, glPolygonMode);
	LOAD_GL_FUNC(PFNGLDRAWELEMENTSPROC, glDrawElements);
	LOAD_GL_FUNC(PFNGLDRAWARRAYSPROC, glDrawArrays);
	LOAD_GL_FUNC(PFNGLBINDVERTEXARRAYPROC, glBindVertexArray);
	LOAD_GL_FUNC(PFNGLGENVERTEXARRAYSPROC, glGenVertexArrays);
	LOAD_GL_FUNC(PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray);
	LOAD_GL_FUNC(PFNGLVERTEXATTRIBPOINTERPROC, glVertexAttribPointer);
	LOAD_GL_FUNC(PFNGLDELETESHADERPROC, glDeleteShader);
	LOAD_GL_FUNC(PFNGLUSEPROGRAMPROC, glUseProgram);
	LOAD_GL_FUNC(PFNGLGETPROGRAMIVPROC, glGetProgramiv);
	LOAD_GL_FUNC(PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog);
	LOAD_GL_FUNC(PFNGLLINKPROGRAMPROC, glLinkProgram);
	LOAD_GL_FUNC(PFNGLATTACHSHADERPROC, glAttachShader);
	LOAD_GL_FUNC(PFNGLCREATEPROGRAMPROC, glCreateProgram);
	LOAD_GL_FUNC(PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog);
	LOAD_GL_FUNC(PFNGLGETSHADERIVPROC, glGetShaderiv);
	LOAD_GL_FUNC(PFNGLCOMPILESHADERPROC, glCompileShader);
	LOAD_GL_FUNC(PFNGLSHADERSOURCEPROC, glShaderSource);
	LOAD_GL_FUNC(PFNGLCREATESHADERPROC, glCreateShader);
	LOAD_GL_FUNC(PFNGLBUFFERDATAPROC, glBufferData);
	LOAD_GL_FUNC(PFNGLBINDBUFFERPROC, glBindBuffer);
	LOAD_GL_FUNC(PFNGLGENBUFFERSPROC, glGenBuffers);
	LOAD_GL_FUNC(PFNGLCLEARPROC, glClear);
	LOAD_GL_FUNC(PFNGLCLEARCOLORPROC, glClearColor);
	LOAD_GL_FUNC(PFNGLVIEWPORTPROC, glViewport);
	LOAD_GL_FUNC(PFNGLDELETEBUFFERSPROC, glDeleteBuffers);
	LOAD_GL_FUNC(PFNGLDELETEVERTEXARRAYSPROC, glDeleteVertexArrays);
	LOAD_GL_FUNC(PFNGLTEXPARAMETERFVPROC, glTexParameterfv);
	LOAD_GL_FUNC(PFNGLBUFFERSUBDATAPROC, glBufferSubData);
	LOAD_GL_FUNC(PFNGLUNIFORM3FVPROC, glUniform3fv);
	LOAD_GL_FUNC(PFNGLUNIFORM1FPROC, glUniform1f);
	LOAD_GL_FUNC(PFNGLVERTEXATTRIBIPOINTERPROC, glVertexAttribIPointer);

	return true;
}
